baseURL = "https://ivanscm.github.io/"
languageCode = "ru-ru"
title = "Блог Григорьева Ивана"
theme = "ivan-blog"
date = "2 January 2006"
datetime = "2 January 2006, в 15:04"
time = "15:04"
disqusShortname = "ivanscm"

[pagination]
  pagerSize = 6

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
category = "categories"

[params]
mainSections = ["posts"]
author = "Ivan Grigoryev"
about = "Добро пожаловать! Меня зовут Григорьев Иван, я Full Stack Developer. В основном пишу на PHP (Nette, Laravel), Python (Django, DRF), Vue (Quasar Framework). Опыт профессиональной разработки более 12 лет."
workLine = "Оказываю консультации по разработке ПО."
  [params.social]
  github = "https://github.com/ivanscm"
  habr = "https://habr.com/ru/users/ivanscm/"
  telegram = "https://t.me/prog_codex"

[menu]
[[menu.main]]
  name = 'Блог'
  url = '/posts/'
  weight = 10
[[menu.main]]
  name = 'Библиотека'
  url = '/books/'
  weight = 20
[[menu.main]]
  name = 'Переводы'
  url = '/translates/'
  weight = 30
